# Generated by Django 5.1.4 on 2024-12-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=32, verbose_name='Articul')),
                ('area', models.FloatField(verbose_name='Square')),
                ('price', models.IntegerField(blank=True, default=0, verbose_name='Price')),
            ],
            options={
                'verbose_name': 'Flat',
                'verbose_name_plural': 'Flats',
                'indexes': [models.Index(fields=['article'], name='realty_flat_article_f5f3ca_idx')],
            },
        ),
    ]
