# Generated by Django 5.1.4 on 2024-12-08 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0002_flat_developer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='developer',
        ),
    ]
