# Generated by Django 5.1.4 on 2024-12-08 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0001_initial'),
        ('realty', '0003_remove_flat_developer'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='developer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flats', to='developers.developer', verbose_name='Developer'),
        ),
    ]
